---
sidebar: sidebar 
permalink: learn-project-dashboard.html 
keywords: projects dashboard, AWS tags, CloudWatch, FSx for ONTAP, Workload Factory, EDA, electronic design automation, volume details, capacity utilization, throughput utilization, IOPS utilization, custom filters 
summary: 了解 Workload Factory for EDA 中的项目仪表板如何帮助您监控和分析 FSx for ONTAP 文件系统和卷的项目存储使用情况。 
---
= 了解 Workload Factory for EDA 中的项目仪表板
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
项目仪表板使 IT 管理员和项目经理能够查看项目如何跨 FSx for ONTAP 文件系统和卷使用存储。它显示存储使用模式，以便您可以在容量或性能问题影响 EDA 模拟之前发现使用最多资源的项目、跟踪成本并调整存储。



== 项目仪表板的工作方式

"项目"仪表板显示链接到您的 AWS 凭据的所有 FSx for ONTAP 卷的 CloudWatch 指标。您可以使用 AWS 标签创建最多五个筛选器，以按项目、团队、应用程序或其他类别组织和查看数据。

控制面板可帮助您：

* 规划产能并了解成本
* 使用数据来决定如何分配资源
* 发现使用大量资源的项目
* 按项目或团队跟踪成本
* 在发生问题之前调整存储空间


有关主动延迟性能监控，请参阅link:learn-latency-monitoring.html["了解延迟监控"]。



=== 收集的 CloudWatch 指标

仪表板将收集并显示以下 CloudWatch 指标：

* *已调配容量*：表示已调配存储容量的卷级指标。
* *已使用容量*：表示已使用存储的卷级指标。
* *平均/最大吞吐量*：计算为指定时间段内 DataReadBytes 和 DataWriteBytes 之和的平均值或最大值。
* *平均/最大 IOPS*：计算为指定时间段内 DataReadOperations、DataWriteOperations 和 MetadataOperations 总和的平均值或最大值。




== 自定义筛选器

自定义筛选器可帮助您整理仪表板数据，以匹配组织的工作方式。按项目、团队或成本中心设置筛选器，这样您就可以快速找到所需的数据，而无需对不相关的信息进行分类。这样可以更轻松地规划容量、跟踪成本并监控性能。

您最多可以根据 AWS 标签配置五个自定义过滤器。

* *筛选器标签名称*：显示在仪表板中的显示名称
* *AWS 标记密钥名称*：资源上使用的实际 AWS 标记密钥
* *选择类型*：单选或多选


如果您未配置任何自定义筛选器，默认筛选器（文件系统、卷类型和时间范围）仍将可用，因此您可以查看和使用仪表板。



=== AWS 标记

AWS 标记是 AWS 资源的元数据。它们可以帮助您以不同的方式对 AWS 资源进行分类，例如按项目、应用程序或业务部门进行分类。

要使用自定义筛选器，请将 AWS 标记添加到符合您需求的 FSx for ONTAP 卷中，例如项目、团队或业务部门的标记。

有关标记的详细信息，请参阅 https://docs.aws.amazon.com/whitepapers/latest/tagging-best-practices/what-are-tags.html["什么是标签？"^]和 https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/overview.html["AWS 资源组标记 API 参考"^]。



== 卷详细信息

控制面板提供查看模式，可帮助您分析不同详细信息级别的存储指标。



=== 总视图

"总计"视图（默认）显示与所选筛选器匹配的所有卷的合并指标。它可以快速概述整体存储性能，包括总容量、IOPS 和吞吐量。

使用此视图可以：

* 了解整体趋势
* 规划未来容量需求
* 报告跨项目或跨团队的总资源消耗




=== 卷视图

卷视图显示各个卷随时间的性能变化。它显示每个指标的前 10 个卷。这有助于您了解哪些卷在选定时间段内使用的资源最多，以及它们的行为方式。

使用此视图可以：

* 找出性能下降的原因
+
** 确定可能需要调整大小的存储卷
** 查看哪些项目或工作负载使用的资源最多






==== 显示的卷指标

当您查看单个卷时，控制面板将显示每个指标的卷总数中的前 10 个卷：

* *卷已用容量*：显示当前已用容量最高的卷。
* *IOPS*：显示选定时间段内平均 IOPS 最高的卷。
* *吞吐量*：显示选定时间段内平均吞吐量最高的卷。



NOTE: 控制面板仅显示每个指标的前 10 个卷。如果您有超过 10 个卷，某些卷可能不会显示在详细视图中。

当相同的卷出现在多个指标中时，控制面板在图例中使用相同的颜色，因此您可以轻松地在不同的指标中跟踪这些卷。



==== 交互式卷数据

将鼠标悬停在图表上可查看特定时间的确切值。这有助于您将性能变化与事件或时间段相关联。详细数据可以帮助您发现性能问题，确认优化是否有效，并向其他人解释资源使用情况。

将鼠标悬停在图形中的任何卷线上时，您可以查看：

* *卷已用容量*：卷名称、该时间点的已用容量和已分配容量
* *IOPS*：卷名称、时间范围内的平均 IOPS 和时间范围内的最大 IOPS
* *吞吐量*：卷名称、时间范围内的平均吞吐量和时间范围内的最大吞吐量




== 相关信息

* link:task-configure-project-dashboard.html["配置项目仪表板"]
* link:task-use-project-dashboard.html["使用项目仪表板"]

